# https://docs.github.com/en/actions

name: "Triage"

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - "opened"

jobs:
  label:
    name: "Label"

    runs-on: "ubuntu-latest"

    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false && (
        github.event.action == 'opened' ||
        github.event.action == 'reopened' ||
        github.event.action == 'synchronize'
      ) && (
        github.actor != 'dependabot[bot]'
      )

    steps:
      - name: "Add labels based on branch name"
        uses: "actions/github-script@v4.0.2"
        with:
          github-token: "${{ secrets.GANSEL_BOT_TOKEN }}"
          script: |
            const branchPrefixLabels = {
              feature: "enhancement",
              fix: "bug",
            }

            const pullRequest = context.payload.pull_request
            const repository = context.repo

            const branchName = pullRequest.head.ref

            const matches = branchName.match(new RegExp('^([^/]+)\/'));

            if (matches instanceof Array && branchPrefixLabels.hasOwnProperty(matches[1])) {
              const label = branchPrefixLabels[matches[1]]

              github.issues.addLabels({
                issue_number: pullRequest.number,
                labels: [
                  label
                ],
                owner: repository.owner,
                repo: repository.repo,
              });
            }
